database new_project

create table person (
    id int primary key generated by default as identity ,
    fullname varchar unique not null ,
    year_of_birth int not null check (year_of_birth >1920 )
);

create table book (
    id int primary key generated by default as identity ,
    title varchar not null ,
    author varchar not null,
    year_of_production int not null,
    id_person int references person(id) on delete cascade 
);

insert into person (fullname, year_of_birth) VALUES
                                                 ('Костенко Петр Анатольевич',1968),
                                                 ('Ворзлов Семён Филипович',1955),
                                                 ('Кривенко Светлана Петровна',1995),
                                                 ('Нестеренко Татьяна Андреевна', 2001),
                                                 ('Самсонова Екатерина Алесандровна',1999),
                                                 ('Кузнецов Андрей Михаилович',1986),
                                                 ('Ткач Виктор Леонидович',1995),
                                                 ('Филипова Анастасия Игорьевна',2002);
												 
												 insert into book (title, author, year_of_production, id_person) VALUES
('Философия Java','Тим Кук',1988,1),
('Пролитая над гнездом кукушки','Андрес Пол',1966,2),
('В окне на краю','Саманта Фокс',1999,1),
('Волк и стая','Серж Антре',2006,3),
('В погоне за успехом','Аллан По',1976,4),
('Супер сила','Мистер С',20001,5),
('Антропология','Ин Джо',1993,2),
('Река у дома','Крани Тейлор',2000,7),
('Сера и порох','Джон Маккейн',2010,6),
('Кто знает?','С С Вайт',2007,3),
('Симпатия барроко','Милена Руж',2016,4),
('Вселенная у нас в руках','Гонфри Изи',1956,4),
('Смех у обрыва','Франкоин Енши',2022,5);